
development:
  adapter: postgresql
  database: dungeons_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: dungeons_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: dungeons_production
  pool: 5
  timeout: 5000
